### ISSUE TITLE
Use same workflow get dif result in 4090/a100

### ISSUE THREAD

**Issue by DamienCz** [Acly/comfyui-inpaint-nodes#101]
I understand that Turbo、Lightning、Hyper cannot be use in fooocus inpaint model ,however i still use Lightning model to remove watermark successful in 4090
then when i put same workflow in a100 (same model same data setting) I get terrible result
can u tell me why?thx

**Comment by Acly** [comment]
no idea, I don't think anybody can answer that without some serious investigation of your systems/install
