### ISSUE TITLE
"Soft Inpainting" feature from A1111 dev branch

### ISSUE THREAD

**Issue by LuLmaster69** [Acly/comfyui-inpaint-nodes#12]
Thank you for greatly expanding the inpainting for ComfyUI.

It is not really an issue but I don't know how to raise this suggestion otherwise.

I was thinking that you may be interested in the new "soft inpainting" feature from the latest dev branch of Automatic1111. It seems that ComfyUI is currently lacking such a feature.

Here's more details on it:
https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/14208

**Comment by Acly** [comment]
I noticed that, and while I'm not 100% sure I think that is how denoise masks have always worked in ComfyUI.
If you use only "VAE Encode (for Inpainting)" you get a binary mask.
But "Set Latent Noise Mask" and relatively new "InpaintModelConditioning" use soft masks to add noise and for conditioning.

**Comment by LuLmaster69** [comment]
Thanks for clarification!

**Comment by nomadoor** [comment]
![InpaintModelConditioning](https://github.com/Acly/comfyui-inpaint-nodes/assets/124905471/e2034f67-7527-49fb-83d1-c63006caf0ae)
[InpaintModelConditioning.json](https://github.com/Acly/comfyui-inpaint-nodes/files/14313199/InpaintModelConditioning.json)
I found it interesting and gave it a try, but it seems that neither InpaintModelConditioning nor Set Latent Noise Mask support non-binary masks.
I apologize if I am mistaken.

**Comment by LuLmaster69** [comment]
Reopening so that people could check if nomadoor's workflow is correct for non-binary masks.

**Comment by Acly** [comment]
You'd see a hard cut if it was rounded into a binary mask. Instead you see some kind of transition, but only for mask values close to 1, it seems to vanish quickly. Exactly how it uses mask values between 0 and 1 I don't know. The A1111 soft mask implements some kind of bleding between denoised and original latent, probably this is different.

![denoise-mask](https://github.com/Acly/comfyui-inpaint-nodes/assets/6485914/d903ec68-3195-4013-929e-37b79c2f3ddc)
Comparison smooth vs binary

**Comment by Acly** [comment]
I think ComfyUI behavior works well enough for masks that are primarily fully opaque or transparent, but use soft edges / feathering at the borders for better transition.
It's not suited if you need intuitive and arbitrary per-pixel denoise strength.

**Comment by LuLmaster69** [comment]
Thanks, hopefully this would clarify things for people who want to implement per-pixel denoise inpainting in ComfyUI.

**Comment by CodeHatchling** [comment]
> Thanks, hopefully this would clarify things for people who may seek to implement per-pixel denoise inpainting in ComfyUI.
> 
> I also noticed that "soft inpainting" in dev Auto1111 with max blur changes the picture beyond the mask, as in the example provided in their pull request thread.

Yes, in contrast to vanilla inpainting, any area within "blur radius" from a masked pixel may be modified. This is intended to help inpaint-sketch by expanding the influence of the denoiser to include all pixels that are affected by the sketch.
