### ISSUE TITLE
"Weights only load failed." when using the outpaint example

### ISSUE THREAD

**Issue by stijlfigurant** [Acly/comfyui-inpaint-nodes#13]
```
Error occurred when executing INPAINT_LoadFooocusInpaint:

Weights only load failed. Re-running `torch.load` with `weights_only` set to `False` will likely succeed, but it can result in arbitrary code execution.Do it only if you get the file from a trusted source. WeightsUnpickler error: Unsupported operand 60
```

For the rest unmodified and got all the same checkpoints afaik.

![image](https://github.com/Acly/comfyui-inpaint-nodes/assets/402389/c767a72f-d6fe-405e-9932-e8717737137e)

**Comment by stijlfigurant** [comment]
NVM worked it out, i had incorrectly downloaded the fooocus models apparentyl

**Comment by g0g5** [comment]
How did you work it out, download all models in that repo and put in same folder?
