### ISSUE TITLE
RuntimeError: shape '[1, 1, 1408, 938]' is invalid for input of size 21131264

### ISSUE THREAD

**Issue by jinnaluo0** [Acly/comfyui-inpaint-nodes#17]
In a workflow, I used this node “LoadImagesFromDir //Inspire”  to passed in multiple images. When running to the node "INPAINT_InpaintWithModel", an error occurred:

[图像擦除_fooocus_seg 2.json](https://github.com/Acly/comfyui-inpaint-nodes/files/14401016/_fooocus_seg.2.json)

ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-inpaint-nodes\nodes.py", line 343, in inpaint
    image, mask = to_torch(image, mask)
                  ^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-inpaint-nodes\util.py", line 13, in to_torch
    mask = mask.reshape(1, 1, mask.shape[-2], mask.shape[-1])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: shape '[1, 1, 1408, 938]' is invalid for input of size 21131264

Prompt executed in 59.13 seconds

**Comment by Acly** [comment]
This looks like an older version, does it still happen with latest update?

**Comment by jinnaluo0** [comment]
After updating the plugin, the error was eliminated

**Comment by jinnaluo0** [comment]
However, when running to this node “INPAINT_VAEEncodeInpaintConditioning”, a new abnormal appeared. The original input was two images, but now it has become four.

No code errors occurred, only the number of images doubled.
