### ISSUE TITLE
Accept Batch

### ISSUE THREAD

**Issue by inferno46n2** [Acly/comfyui-inpaint-nodes#20]
Hi there

Fantastic work!

Could this be modified to accepted a batch of images though? At the moment if I feed it anymore than 1 image I get a size of tensors >1 error.

Would be great to be able to use this with Hotshot / AnimateDiff.

**Comment by chlebaczysko** [comment]
from __future__ import annotations
from typing import Any
import numpy as np
import torch
import torch.jit
import torch.nn.functional as F
from torch import Tensor
from tqdm import trange

from comfy.utils import ProgressBar
from comfy.model_patcher import ModelPatcher
from comfy.model_base import BaseModel
from comfy.model_management import cast_to_device, get_torch_device
from comfy_extras.chainner_models.types import PyTorchModel
import comfy_extras.chainner_models.model_loading
import comfy.utils
import comfy.lora
import folder_paths
import nodes

from . import mat
from .util import (
    gaussian_blur,
    binary_erosion,
    make_odd,
    to_torch,
    to_comfy,
    resize_square,
    undo_resize_square,
)

class InpaintHead(torch.nn.Module):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.head = torch.nn.Parameter(torch.empty(size=(320, 5, 3, 3), device="cpu"))

    def forward(self, x):
        x = F.pad(x, (1, 1, 1, 1), "replicate")
        return F.conv2d(input=x, weight=self.head)

def load_fooocus_patch(lora: dict, to_load: dict):
    patch_dict = {}
    loaded_keys = set()
    for key in to_load.values():
        if value := lora.get(key, None):
            patch_dict[key] = ("fooocus", value)
            loaded_keys.add(key)

    not_loaded = sum(1 for x in lora if x not in loaded_keys)
    print(
        f"[ApplyFooocusInpaint] {len(loaded_keys)} Lora keys loaded, {not_loaded} remaining keys not found in model."
    )
    return patch_dict

original_calculate_weight = ModelPatcher.calculate_weight
injected_model_patcher_calculate_weight = False

def calculate_weight_patched(self: ModelPatcher, patches, weight, key):
    remaining = []

    for p in patches:
        alpha, v, strength_model = p

        is_fooocus_patch = isinstance(v, tuple) and len(v) == 2 and v[0] == "fooocus"
        if not is_fooocus_patch:
            remaining.append(p)
            continue

        if alpha != 0.0:
            v = v[1]
            w1 = cast_to_device(v[0], weight.device, torch.float32)
            if w1.shape == weight.shape:
                w_min = cast_to_device(v[1], weight.device, torch.float32)
                w_max = cast_to_device(v[2], weight.device, torch.float32)
                w1 = (w1 / 255.0) * (w_max - w_min) + w_min
                weight += alpha * cast_to_device(w1, weight.device, weight.dtype)
            else:
                print(
                    f"[ApplyFooocusInpaint] Shape mismatch {key}, weight not merged ({w1.shape} != {weight.shape})"
                )

    if len(remaining) > 0:
        return original_calculate_weight(self, remaining, weight, key)
    return weight

def inject_patched_calculate_weight():
    global injected_model_patcher_calculate_weight
    if not injected_model_patcher_calculate_weight:
        print(
            "[comfyui-inpaint-nodes] Injecting patched comfy.model_patcher.ModelPatcher.calculate_weight"
        )
        ModelPatcher.calculate_weight = calculate_weight_patched
        injected_model_patcher_calculate_weight = True

class LoadFooocusInpaint:
    @classmethod
    def INPUT_TYPES(s):
        return {
            "required": {
                "head": (folder_paths.get_filename_list("inpaint"),),
                "patch": (folder_paths.get_filename_list("inpaint"),),
            }
        }

    RETURN_TYPES = ("INPAINT_PATCH",)
    CATEGORY = "inpaint"
    FUNCTION = "load"

    def load(self, head: str, patch: str):
        head_file = folder_paths.get_full_path("inpaint", head)
        inpaint_head_model = InpaintHead()
        sd = torch.load(head_file, map_location="cpu")
        inpaint_head_model.load_state_dict(sd)

        patch_file = folder_paths.get_full_path("inpaint", patch)
        inpaint_lora = comfy.utils.load_torch_file(patch_file, safe_load=True)

        return ((inpaint_head_model, inpaint_lora),)

class ApplyFooocusInpaint:
    @classmethod
    def INPUT_TYPES(s):
        return {
            "required": {
                "model": ("MODEL",),
                "patch": ("INPAINT_PATCH",),
                "latent": ("LATENT",),
            }
        }

    RETURN_TYPES = ("MODEL",)
    CATEGORY = "inpaint"
    FUNCTION = "patch"

    def patch(
        self,
        model: ModelPatcher,
        patch: tuple[InpaintHead, dict[str, Tensor]],
        latent: dict[str, Any],
    ):
        base_model: BaseModel = model.model
        latent_pixels = base_model.process_latent_in(latent["samples"])
        noise_mask = latent["noise_mask"].round()

        latent_mask = F.max_pool2d(noise_mask, (8, 8)).round().to(latent_pixels)

        inpaint_head_model, inpaint_lora = patch
        feed = torch.cat([latent_mask, latent_pixels], dim=1)
        inpaint_head_model.to(device=feed.device, dtype=feed.dtype)
        inpaint_head_feature = inpaint_head_model(feed)

        def input_block_patch(h, transformer_options):
            if transformer_options["block"][1] == 0:
                h = h + inpaint_head_feature.to(h)
            return h

        lora_keys = comfy.lora.model_lora_keys_unet(model.model, {})
        lora_keys.update({x: x for x in base_model.state_dict().keys()})
        loaded_lora = load_fooocus_patch(inpaint_lora, lora_keys)

        m = model.clone()
        m.set_model_input_block_patch(input_block_patch)
        patched = m.add_patches(loaded_lora, 1.0)

        not_patched_count = sum(1 for x in loaded_lora if x not in patched)
        if not_patched_count > 0:
            print(f"[ApplyFooocusInpaint] Failed to patch {not_patched_count} keys")

        inject_patched_calculate_weight()
        return (m,)

class VAEEncodeInpaintConditioning:
    @classmethod
    def INPUT_TYPES(s):
        return {
            "required": {
                "positive": ("CONDITIONING",),
                "negative": ("CONDITIONING",),
                "vae": ("VAE",),
                "pixels": ("IMAGE",),
                "mask": ("MASK",),
            }
        }

    RETURN_TYPES = ("CONDITIONING", "CONDITIONING", "LATENT", "LATENT")
    RETURN_NAMES = ("positive", "negative", "latent_inpaint", "latent_samples")
    FUNCTION = "encode"
    CATEGORY = "inpaint"

    def encode(self, positive, negative, vae, pixels, mask):
        positive, negative, latent = nodes.InpaintModelConditioning().encode(
            positive, negative, pixels, vae, mask
        )
        latent_inpaint = dict(
            samples=positive[0][1]["concat_latent_image"],
            noise_mask=latent["noise_mask"].round(),
        )
        return (positive, negative, latent_inpaint, latent)

class MaskedFill:
    @classmethod
    def INPUT_TYPES(s):
        return {
            "required": {
                "image": ("IMAGE",),
                "mask": ("MASK",),
                "fill": (["neutral", "telea", "navier-stokes"],),
                "falloff": ("INT", {"default": 0, "min": 0, "max": 8191, "step": 1}),
            }
        }

    RETURN_TYPES = ("IMAGE",)
    CATEGORY = "inpaint"
    FUNCTION = "fill"

    def fill(self, image: Tensor, mask: Tensor, fill: str, falloff: int):
        alpha = mask.expand(1, *mask.shape[-2:]).floor()
        falloff = make_odd(falloff)
        if falloff > 0:
            erosion = binary_erosion(alpha, falloff)
            alpha = alpha * gaussian_blur(erosion, falloff)

        if fill == "neutral":
            image = image.detach().clone()
            m = (1.0 - alpha).squeeze(1)
            for i in range(3):
                image[:, :, :, i] -= 0.5
                image[:, :, :, i] *= m
                image[:, :, :, i] += 0.5
        else:
            import cv2

            method = cv2.INPAINT_TELEA if fill == "telea" else cv2.INPAINT_NS
            alpha_np = alpha.squeeze(0).cpu().numpy()
            alpha_bc = alpha_np.reshape(*alpha_np.shape, 1)
            for slice in image:
                image_np = slice.cpu().numpy()
                filled_np = cv2.inpaint(
                    (255.0 * image_np).astype(np.uint8),
                    (255.0 * alpha_np).astype(np.uint8),
                    3,
                    method,
                )
                filled_np = filled_np.astype(np.float32) / 255.0
                filled_np = image_np * (1.0 - alpha_bc) + filled_np * alpha_bc
                slice.copy_(torch.from_numpy(filled_np))

        return (image,)

class MaskedBlur:
    @classmethod
    def INPUT_TYPES(s):
        return {
            "required": {
                "image": ("IMAGE",),
                "mask": ("MASK",),
                "blur": ("INT", {"default": 255, "min": 3, "max": 8191, "step": 1}),
                "falloff": ("INT", {"default": 0, "min": 0, "max": 8191, "step": 1}),
            }
        }

    RETURN_TYPES = ("IMAGE",)
    CATEGORY = "inpaint"
    FUNCTION = "fill"

    def fill(self, image: Tensor, mask: Tensor, blur: int, falloff: int):
        blur = make_odd(blur)
        falloff = min(make_odd(falloff), blur - 2)
        image, mask = to_torch(image, mask)

        original = image.clone()
        alpha = mask.floor()
        if falloff > 0:
            erosion = binary_erosion(alpha, falloff)
            alpha = alpha * gaussian_blur(erosion, falloff)
        alpha = alpha.repeat(1, 3, 1, 1)

        image = gaussian_blur(image, blur)
        image = original + (image - original) * alpha
        return (to_comfy(image),)

class LoadInpaintModel:
    @classmethod
    def INPUT_TYPES(s):
        return {
            "required": {
                "model_name": (folder_paths.get_filename_list("inpaint"),),
            }
        }

    RETURN_TYPES = ("INPAINT_MODEL",)
    CATEGORY = "inpaint"
    FUNCTION = "load"

    def load(self, model_name: str):
        model_file = folder_paths.get_full_path("inpaint", model_name)
        if model_file is None:
            raise RuntimeError(f"Model file not found: {model_name}")
        if model_file.endswith(".pt"):
            sd = torch.jit.load(model_file, map_location="cpu").state_dict()
        else:
            sd = comfy.utils.load_torch_file(model_file, safe_load=True)

        if "synthesis.first_stage.conv_first.conv.resample_filter" in sd:  # MAT
            model = mat.load(sd)
        else:
            model = comfy_extras.chainner_models.model_loading.load_state_dict(sd)
        model = model.eval()
        return (model,)

class InpaintWithModel:
    @classmethod
    def INPUT_TYPES(s):
        return {
            "required": {
                "inpaint_model": ("INPAINT_MODEL",),
                "image": ("IMAGE",),
                "mask": ("MASK",),
                "seed": ("INT", {"default": 0, "min": 0, "max": 0xFFFFFFFFFFFFFFFF}),
            },
            "optional": {
                "optional_upscale_model": ("UPSCALE_MODEL",),
            },
        }

    RETURN_TYPES = ("IMAGE",)
    CATEGORY = "inpaint"
    FUNCTION = "inpaint"

    def inpaint(
        self,
        inpaint_model: PyTorchModel,
        image: Tensor,
        mask: Tensor,
        seed: int,
        optional_upscale_model=None,
    ):
        if inpaint_model.model_arch == "MAT":
            required_size = 512
        elif inpaint_model.model_arch == "LaMa":
            required_size = 256
        else:
            raise ValueError(f"Unknown model_arch {inpaint_model.model_arch}")

        device = get_torch_device()
        inpaint_model.to(device)
        image = image.to(device)
        mask = mask.to(device)

        # Przetwarzanie wsadowe
        batch_image = []
        batch_size = image.size(0)
        pbar = ProgressBar(batch_size)

        for i in trange(batch_size):
            work_image, work_mask = image[i:i+1], mask[i:i+1]  # Przetwarzanie pojedynczych próbek wsadowo
            work_image, work_mask, original_size = resize_square(
                work_image, work_mask, required_size
            )
            work_mask = work_mask.floor()

            torch.manual_seed(seed)
            work_image = inpaint_model(work_image, work_mask)

            if optional_upscale_model is not None:
                # Przetwarzanie skalowania opcjonalnego wsadowo
                work_image = work_image.movedim(1, -1)
                work_image = upscaler.upscale(
                    upscaler, optional_upscale_model, work_image
                )
                work_image = work_image[0].movedim(-1, 1)

            work_image = undo_resize_square(work_image, original_size)
            work_image = image[i] + (work_image - image[i]) * mask[i].floor()

            batch_image.append(work_image)

            pbar.update(1)

        inpaint_model.cpu()
        result = torch.cat(batch_image, dim=0)
        return (to_comfy(result),)

**Comment by chlebaczysko** [comment]
its not that easy, i think cross attention patch is needed, you can get it in ipadapterplus code, just adjust

**Comment by chlebaczysko** [comment]
can someone tell what changes must be done ? add batch_size? maybe attention with animatediff code patch that we can find in ipadapter?

**Comment by chlebaczysko** [comment]
i think they need to implement animatediff patch but this patch require cross attention so they need to implement both at some place in MAT.py file somewhere between inpaint and forward functions (not sure which)
  h = h + inpaint_head_feature.to(h)
RuntimeError: The size of tensor a (4) must match the size of tensor b (2) at non-singleton dimension 0
its related somewhat
i might be wrong tho, i cant code at all

**Comment by chlebaczysko** [comment]
need to merge code of ipadapter with code of mat.py, important things are adapt MLP to use cross attention and self attention at once, adapt conv's, adapt shapes, adapt animatediff patch that works on attention - it need attention to set similar weightset or something like that so image is similar between batch, oh batch - unfold_batch is the command, but need to implement logic, with my python knowlege [ 0 ], month of work : P 
could be great to have some thinking help

**Comment by chlebaczysko** [comment]
merging ipadapter code with fooocus and mat.py should do work
we need working batch_size, unfold_batch actually ?
cross attention using embedings made from latents merged by layers with windowattention and added animateddiff patch
doable
have to basically rewrite whole code but doable

**Comment by chlebaczysko** [comment]
`from __future__ import annotations
import numpy as np
import torch
import torchvision.transforms as TT
from typing import Any
import tqdm

from comfy.utils import ProgressBar
from comfy.model_patcher import ModelPatcher, set_model_input_block_patch
from comfy.model_management import cast_to_device, get_torch_device
from comfy_extras.chainner_models.model_loading import load_state_dict_from_file
import folder_paths
from .util import (
    gaussian_blur,
    binary_erosion,
    make_odd,
    to_torch,
    to_comfy,
    resize_square,
    undo_resize_square,
)
from comfy.lora import ModelLoraKeysUnet
import torchvision.nn as nn
import math
class CrossAttentionPatch:
    def __init__(self, weights, fooocus, number_of_conditions=0, conditional_weights=None, unconditional_weights=None, weighting_type="original", mask=None, sigma_start=0.0, sigma_end=1.0, unfold_batch=False):
        # Initialize class variables
        self.number = number_of_conditions + len(weights)
        self.weights = weights
        self.fooocus = fooocus
        self._set_new_condition(*args if args else (None, None))  # Allow for optional arguments in the set_new_condition method
        self.k_key = f"{self.number * 2 + 1}"
        self.v_key = f"{self.number * 2 + 1}"
        self.q_key = f"{len(weights) + self.number}_query_ip"
        
    def set_new_condition(self, weight, Fooocus, number, cond=None, uncond=None, weight_type="original", mask=None, sigma_start=0.0, sigma_end=1.0):
        self.weights.append(weight)
        self.Fooocuss.append(Fooocus)
        self._set_new_condition(number, cond, uncond, weight_type, mask, sigma_start, sigma_end)
        
    def _set_new_condition(self, number, cond=None, uncond=None, weight_type="original", mask=None, sigma_start=0.0, sigma_end=1.0):
        self.number += number
        if len(self.weights) > 0:
            if cond is not None:
                self.conds.append(cond)
                self._update_kvs(len(self.weights)-1, "cond")
            if uncond is not None:
                self.unconds.append(uncond)
                self._update_kvs(len(self.weights)-1, "uncond")
            self.weight_type.append(weight_type)
            self.masks.append(torch.zeros((*utils.image_shape(),), dtype=torch.float32)) if mask is None else mask  # update masks assignment
            self.sigma_start.append(sigma_start)
            self.sigma_end.append(sigma_end)
        
    def _update_kvs(self, window_index, key):
        if not hasattr(self.Fooocuss[window_index], f"ip_layers.to_{key}"):  # add missing 'hasattr' check
            raise AttributeError("Missing required IP layer for provided Fooocus instance.")

        k = getattr(self.Fooocuss[window_index].ip_layers, f"to_{key}") if hasattr(getattr(self.Fooocuss[window_index], 'ip_layers'), "to_"+key) else None  # update ip_layers access
        self.__dict__[f'{self.k_key}_{window_index}'] = k
        v = getattr(self.Fooocuss[window_index].ip_layers, "to_v") if "to_v" in dir(getattr(self.Fooocuss[window_index], 'ip_layers')) else None  # update to_v access
        self.__dict__[f'{self.v_key}_{window_index}'] = v
        
    def __call__(self, q, context_attn2=None, value_attn2=None, extra_options={}):
        org_dtype = q.dtype

        cond_or_uncond = extra_options["cond_or_uncond"]
        sigma = extra_options["sigmas"][0] if "sigmas" in extra_options else None
        sigma = sigma.item() if sigma is not None else 999999999.9

        q = to_torch(q)
        b, qs = q.shape[0], q.shape[1]

        for window_index, (weight, Fooocus, cond, uncond, mask, sigma_start, sigma_end) in enumerate(zip(self.weights, self.Fooocuss, self.conds, self.unconds, self.masks, self.sigma_start, self.sigma_end)):
            if sigma > sigma_start or sigma < sigma_end:  # update sigma comparison logic to avoid skipping unmatched sigmas
                continue
            ips = Fooocus(q, cond, uncond) if not self.unfold_batch else [Fooocus(q[:, i], cond[i], uncond[i]) for i in range(b)]  # update Fooocus instantiation logic
            if self._should_apply_mask(ips):
                q = self._apply_masked_fill(q, mask, falloff=extra_options["falloff"]) if "ad_params" not in extra_options or len(self.conds) <= 1 else [self._apply_masked_fill(q[:, i], mask[i], falloff=extra_options["falloff"]) for i in range(b)]
            self_attn = optimized_attention(ips, q, attn_weights=self.weights) if "ad_params" not in extra_options else [optimized_attention(ips[i], q[:, i], attn_weights=[w for w in self.weights][i]) for i in range(b)]  # update optimized_attention function call to accommodate unfolded batch
            context_attns = context_attn2[:len(cond) + len(uncond)] if not self.unfold_batch else [context_attn2[j] for j in range(b)]  # update context_attn2 processing logic
            cross_value_atts = v if "ad_params" not in extra_options and not self.unfold_batch or len(self.conds) <= 1 else [v[i][0] for i in range(len(context_attns))] # update cross_value_atts processing logic
            cross_atts = self._apply_cross_attention(q, context_attns, value_attn2, {"cond_or_uncond": cond_or_uncond}) if "ad_params" not in extra_options else [self._apply_masked_blur(q[i], cross_atts[i][0].unsqueeze(1), falloff=extra_options["falloff"]) for i in range(b)] # update apply_cross_attention function call to accommodate unfolded batch
            k.append(self._rearrange_k(torch.cat([to_torch(np.reshape(c, (1, -1))) for c in cross_atts], dim=0)) if "ad_params" not in extra_options else self._rearrange_ks([to_torch(np.reshape(c[i][0], (1, -1))) for c in cross_attns])) # update k rearrangement logic
            v.append(self._rearrange_v(cross_value_atts)) if "ad_params" not in extra_options else [self._rearrange_vs([c[0][0] for c in cross_attn2])] # update v rearrangement logic
            attentions = self._concatenate_all_windows_outputs() if "ad_params" not in extra_options else [torch.cat(self._window_attention_output[i][0].unsqueeze(1) for i in range(b))] # update attention outputs concatenation logic to accommodate unfolded batch
            attn_weights = self.conds + [self.unconds]*len(self.conds)*2 if "ad_params" not in extra_options else list(itertools.chain(*[attn_weight for cond in self.conds]*3)) # update attention weights processing logic to accommodate unfolded batch
            attentions, _ = optimized_attention(q, torch.cat([self._concatenate_all_windows_outputs()[i] for i in range(b)], dim=1), attn_weights, extra_options["n_heads"]) # update optimized attention call to accommodate unfolded batch
            self._store_window_outputs(attentions[:len(self.conds+2)+len(self.unconds)*2]) # update store window outputs logic to accommodate unfolded batch
        output = torch.cat([torch.chunk(k[j], 3, dim=-1)[0].permute(2, 0, 1).unsqueeze(0) for j in range(len(self.conds+2)+len(self.unconds)*2)] + [v[-1][:qs] for _ in range(len(self.weights))]) # update output processing logic to accommodate unfolded batch
        if "ad_params" not in extra_options:  # remove redundant ad_params check from return statement
            attention, attn_weights = optimized_attention(q, torch.cat([k[i][0] for i in range(len(self.conds+2)+len(self.unconds)*2)] + [v[-1]], dim=1), attn_weights)
            return attention, attn_weights[-1], output # update return statement to include final attention and output tensors
        else:  # add missing return statements for unfolded batch case
            attention = torch.stack([attentions[i].unsqueeze(0) for i in range(len(self.conds))]) if "ad_params" not in extra_options else [torch.cat(attentions[:len(self.conds)+2][i] for i in range(b)), attentions[-1]] # update attention return statement to accommodate unfolded batch
            attn_weights = torch.stack([[attn_weight[j] for j in self.unconds] + [attn_weight[len(self.unconds)]]*2 for i, attn_weight in enumerate(attentions[:-1])]) if "ad_params" not in extra_options else torch.stack([torch.cat([attn_weights[i][j] for j in range(batch_size)], dim=0).unsqueeze(dim=(len(self.unconds)+2)) for i, attn_weight in enumerate(attentions[:-1])])
            return attention, torch.stack([torch.cat([v[i][j] for j in range(batch_size)], dim=0).unsqueeze(dim=(len(self.unconds)+3)) for i in range(len(self.weights))]), attentions[-1].unsqueeze(dim=(len(self.unconds)*2+len(self.conds)+2))
class FooocusModelLoader:
    @classmethod
    def INPUT_TYPES(cls):
        return {"required": {"Fooocus_file": (folder_paths.get_filename_list("Fooocus"), )}} # remove redundant comma from input types list
        
    RETURN_TYPES = ("Fooocus",)
    FUNCTION = "load_Fooocus_model"
    CATEGORY = "Fooocus"

    def load_Fooocus_model(self, Fooocus_file):  # update function name to match class method naming convention
        ckpt_path = folder_paths.get_full_path("Fooocus", Fooocus_file)

        model = load_state_dict_from_file(ckpt_path, map_location="cpu") # add missing import statement for 'load_state_dict_from_file' function

        if "synthesis.first_stage.conv_first.conv.resample_filter" in model:  # MAT
            model = mat.load(model)
        else:
            model = comfy_extras.chainner_models.model_loading.load_state_dict(model)
        model = model.eval()
        return (model,)
class FooocusApply:
    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "model": ("MODEL",),
                "patch": ("INPAINT_PATCH",),
                "latent": ("LATENT",),
            }
        }
        
    RETURN_TYPES = ("MODEL",)
    CATEGORY = "Fooocus"
    FUNCTION = "apply_Fooocus"

    def apply_Fooocus(  # update function name to match class method naming convention and adjust input order
        self, model: ModelPatcher, patch: tuple[InpaintHead, dict[str, Tensor]], latent: dict[str, Any]):
        base_model = model.model
        latent_pixels = cast_to_device(base_model.process_latent_in(latent["samples"]), device=get_torch_device()) # use 'cast_to_device' instead of 'to' for correct conversion
        noise_mask = latent["noise_mask"].round()

        latent_mask = F.max_pool2d(noise_mask, (8, 8)).unsqueeze(1).repeat((1, len(latent_pixels[0].shape[-2:]))) # change 'to' to 'unsqueeze' for correct tensor creation
        latent_mask = latent_mask.round().cuda() if device != "cpu" else latent_mask

        inpaint_head_model, inpaint_lora = patch
        feed = torch.cat([latent_mask, latent_pixels], dim=1) # update 'feed' creation to include proper tensor concatenation and device assignment
        feed = cast_to_device(feed, device) if device != "cpu" else feed  # add missing conversion for feed tensor to the correct device

        inpaint_head_feature = inpaint_head_model(cast_to_device(F.pad(latent_mask, (1, 1, 1, 1), "replicate").unsqueeze(0), device)) if "ad_params" not in extra_options or len(self.conds) <= 1 else [inpaint_head_model(cast_to_device(F.pad(latent_mask[i], (1, 1, 1, 1), "replicate").unsqueeze(0).cuda() if device != "cpu" else latent_mask[i].repeat((batch_size, 1, 1, 1)) for i in range(len(latent_pixels))])] # update feed processing logic to accommodate unfolded batch
        ips = [Fooocus(q.unsqueeze(0), cond, uncond) if not self.unfold_batch else [Fooocus(q[:, i], cond[i], uncond[i]) for i in range(len(latent_pixels))] for q, (cond, uncond) in zip(latent_pixels, patch)] # update ips instantiation logic to accommodate unfolded batch
        attentions = []
        patched_models = [model.clone() for i in range(len(ips))] if self.unfold_batch else [model] * len(ips) # create a list of cloned models for patching in the case of an unfolded batch

        for model, ips, head_feature in zip(patched_models, ips, inpaint_head_feature):
            set_model_input_block_patch(model, (lambda x: self._apply_masked_fill(x[0], x[1], falloff=extra_options["falloff"]) if "ad_params" not in extra_options or len(ips) <= 1 else [self._apply_masked_fill(x[0][i], x[1][i], falloff=extra_options["falloff"]) for i in range(len(latent_pixels))])) # update input block patching logic to accommodate unfolded batch
            patches = ips[-1] + self.weights * (ips[:-1]) if "ad_params" not in extra_options else [ips[i][0] for i in range(len(ips) - 1)] # update patches creation logic to accommodate unfolded batch
            model.add_patches(*patches, 1.0, merge="sum") # add model patching with the new patches and merging method
            attentions.append([model.get_patch(p) for p in patches]) # store the patched models' attention weights for future use
        
        self._store_window_outputs(*attentions, model=model) # update 'self._store_window_outputs' function call to accommodate unfolded batch

    def apply_patch(self, patch_kwargs):
        if not self.is_sdxl:
            for id in [1,2,4,5,7,8]:
                set_model_patch_replace(self.work_model, patch_kwargs, ("input", id))
                patch_kwargs["number"] += 1
            for id in [3,4,5,6,7,8,9,10,11]:
                set_model_patch_replace(self.work_model, patch_kwargs, ("output", id))
                patch_kwargs["number"] += 1
            set_model_patch_replace(self.work_model, patch_kwargs, ("middle", 0))
        else:
            for id in [4,5,7,8]:
                block_indices = range(2) if id in [4, 5] else range(10) 
                for index in block_indices:
                    set_model_patch_replace(self.work_model, patch_kwargs, ("input", id, index))
                    patch_kwargs["number"] += 1
            for id in range(6):
                block_indices = range(2) if id in [3, 4, 5] else range(10) 
                for index in block_indices:
                    set_model_patch_replace(self.work_model, patch_kwargs, ("output", id, index))
                    patch_kwargs["number"] += 1
            for index in range(10):
                set_model_patch_replace(self.work_model, patch_kwargs, ("middle", 0, index))
                patch_kwargs["number"] += 1

class InpaintHead(nn.Module):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.head = nn.Parameter(torch.empty(size=(320, 5, 3, 3), device="cpu"))

    def forward(self, x):
        x = F.pad(x, (1, 1, 1, 1), "replicate")
        return nn.functional.conv2d(input=x, weight=self.head)

class LoadFooocusInpaint:
    @classmethod
    def INPUT_TYPES(s):
        return {
            "required": {
                "head": (folder_paths.get_filename_list("inpaint"),),
                "patch": (folder_paths.get_filename_list("inpaint"),),
            }
        }

    RETURN_TYPES = ("INPAINT_PATCH",)
    FUNCTION = "load"
    CATEGORY = "inpaint"

    def load(self, head: str, patch: str):
        head_file = folder_paths.get_full_path("inpaint", head)
        inpaint_head_model = InpaintHead()
        sd = torch.load(head_file, map_location="cpu")
        inpaint_head_model.load_state_dict(sd)

        patch_file = folder_paths.get_full_path("inpaint", patch)
        inpaint_lora = comfy.utils.load_torch_file(patch_file, safe_load=True)

        return ((inpaint_head_model, inpaint_lora),)

class ApplyFooocusInpaint:
    @classmethod
    def INPUT_TYPES(s):
        return {
            "required": {
                "model": ("MODEL",),
                "patch": ("INPAINT_PATCH",),
                "latent": ("LATENT",),
            }
        }

    RETURN_TYPES = ("MODEL",)
    CATEGORY = "Fooocus"
    FUNCTION = "patch"

    def patch(
        self,
        model: ModelPatcher,
        patch: tuple[InpaintHead, dict[str, Tensor]],
        latent: dict[str, Any],
    ):
        base_model: BaseModel = model.model
        latent_pixels = base_model.process_latent_in(latent["samples"])
        noise_mask = latent["noise_mask"].round()

        latent_mask = F.max_pool2d(noise_mask, (8, 8)).round().to(latent_pixels)

        inpaint_head_model, inpaint_lora = patch
        feed = torch.cat([latent_mask, latent_pixels], dim=1)
        inpaint_head_feature = inpaint_head_model(feed)

        def input_block_patch(h, transformer_options):
            if transformer_options["block"][1] == 0:
                h = h + inpaint_head_feature.to(h)
            return h

        lora_keys = ModelLoraKeysUnet().get_lora_keys(model.model)
        loaded_lora = load_fooocus_patch(inpaint_lora, lora_keys)

        m = model.clone()
        m.set_model_input_block_patch(input_block_patch)
        patched = m.add_patches(loaded_lora, 1.0)

        not_patched_count = sum(1 for x in loaded_lora if x not in patched)
        if not_patched_count > 0:
            print(f"[ApplyFooocusInpaint] Failed to patch {not_patched_count} keys")

        inject_patches()
        return (m,)

class VAEEncodeInpaintConditioning:
    @classmethod
    def INPUT_TYPES(s):
        return {
            "required": {
                "positive": ("CONDITIONING",),
                "negative": ("CONDITIONING",),
                "vae": ("VAE",),
                "pixels": ("IMAGE",),
                "mask": ("MASK",),
            }
        }

    RETURN_TYPES = ("CONDITIONING", "CONDITIONING", "LATENT", "LATENT")
    RETURN_NAMES = ("positive", "negative", "latent_inpaint", "latent_samples")
    FUNCTION = "encode"
    CATEGORY = "inpaint"

    def encode(self, positive, negative, vae, pixels, mask):
        positive, negative, latent = n.InpaintModelConditioning().encode(positive, negative, pixels, vae, mask)
        latent_inpaint = {"samples": positive[0][1], "noise_mask": latent["noise_mask"].round()}
        return (positive, negative, latent_inpaint, latent)

class MaskedFill:
    @classmethod
    def INPUT_TYPES(s):
        return {
            "required": {
                "image": ("IMAGE",),
                "mask": ("MASK",),
                "fill": (["neutral", "telea", "navier-stokes"],),
                "sigma": ("FLOAT", { "min": 0.0, "max": 1.0 }),
            }
        }

    RETURN_TYPES = ("IMAGE",)
    FUNCTION = "fill"
    CATEGORY = "inpaint"

    def fill(self, image, mask, fill="neutral", sigma=0.0):
        if fill == "neutral":
            filled = nn.functional.interpolate(image, scale_factor=8, mode="nearest").to(mask)
            return (filled,)
        elif fill == "telea":
            from patch_telea import patch_telea
            filled = patch_telea(image, mask)
            return (filled,)
        elif fill == "navier-stokes":
            from patch_navier_stokes import patch_navier_stokes
            filled = patch_navier_stokes(image, mask)
            return (filled,)

        raise ValueError(f"Unknown fill option {fill}")

class SaveInpaintMask:
    @classmethod
    def INPUT_TYPES(s):
        return {
            "required": {
                "mask": ("MASK",),
                "sigma": ("FLOAT", { "min": 0.0, "max": 1.0 }),
            }
        }

    FUNCTION = "save"
    CATEGORY = "inpaint"

    def save(self, mask, sigma):
        from comfy import io
        from comfy.tensor_helpers import tensor_to_image
        import os

        mask_image = tensor_to_image(mask)
        io.image_save(mask_image, os.path.join(folder_paths.get_folder_path("inpaint"), f"mask_{sigma:.6f}.png"))

class WindowAttentionOutput(nn.Module):
    def __init__(self, output_size, output_len):
        super().__init__()
        self.output_size = output_size
        self.output_len = output_len

    def forward(self, x, output_window_index):
        output_images = []
        for index in range(x.shape[1]):
            output_images.append(self._extract_output_image(x[:, index], output_window_index))
        return torch.stack(output_images)

    def _extract_output_image(self, x, output_window_index):
        return x

class WindowCrossAttentionOutput(WindowAttentionOutput):
    def forward(self, x, output_window_index):
        return torch.stack([self._extract_output_image(x[:, index], output_window_index) for index in range(x.shape[1])])

class AnimatedDiffSlidingWindowAttention(CrossAttentionPatch):
    def __init__(self, weights, Fooocus, number, conds=None, unconds=None, weight_type="original", mask=None, sigma_start=0.0, sigma_end=1.0, unfold_batch=False):
        super().__init__(weights, Fooocus, number, conds, unconds, weight_type, mask, sigma_start, sigma_end, unfold_batch)
        self.sliding_window = None

    def forward(self, q, context_attn2=None, value_attn2=None, extra_options={}):
        with ProgressBar("Sliding window cross attention", show_on_tty=True):
            self.sliding_window = WindowCrossAttentionOutput(q.shape[-1], len(self.weights))

            def init_progress():
                self.sliding_window_progress = ProgressBar(
                    "Animated diff sliding window",
                    max=math.prod(q.shape[-2:]),
                    show_on_tty=True,
                )
                self.sliding_window_progress.update(0)

            def advance_progress(batch_size, progress):
                self.sliding_window_progress.update(
                    self.sliding_window_progress.value + batch_size
                )

            self.sliding_window_progress = None

            if self.unfold_batch:
                for i in range(q.shape[0]):
                    for batch_index in range(0, len(context_attn2)):
                        if self.sliding_window_progress is None:
                            init_progress()

                        self.sliding_window_progress.update(
                            self.sliding_window_progress.value + batch_index
                        )
            else:
                init_progress()

            return super().forward(q, context_attn2, value_attn2, extra_options)
`

people, does it look any good ?
im trying to adapt code for cross and window attention with sliding window and animatediff with unfold batch and full batch size support, have to merge heads of layers with weights from patched model + embeding heads from latent
