### ISSUE TITLE
Cushy Studio integration

### ISSUE THREAD

**Issue by rvion** [Acly/comfyui-inpaint-nodes#21]
Hi there, I'm the creator of https://github.com/rvion/cushystudio
currently looking forward adding built-in apps for inpaint / outpaint.
was considering using your custom nodes; interested to help ?
end-goal is to have them perfectly integrated with the unified canvas :)

**Comment by Acly** [comment]
Hey, I've seen this project, it's pretty cool!
I've got work lined up to last years though developing the Krita plugin (that was also my motivation for creating those nodes, after getting tired of waiting for someone else to do it)
