### ISSUE TITLE
Error when executing INPAINT_LoadFooocusInpaint:

### ISSUE THREAD

**Issue by jonaaathan** [Acly/comfyui-inpaint-nodes#25]
when executing INPAINT_LoadFooocusInpaint:

Weights only load failed. Re-running `torch.load` with `weights_only` set to `False` will likely succeed, but it can result in arbitrary code execution.Do it only if you get the file from a trusted source. WeightsUnpickler error: Unsupported operand 118

`raise pickle.UnpicklingError(UNSAFE_MESSAGE + str(e)) from None`
--- 

I had download the head file from here. https://huggingface.co/lllyasviel/fooocus_inpaint/blob/main/fooocus_inpaint_head.pth 

it showed `pickle data was truncated` earlier then I thought it had some issues so i manually updated download them manually and upload to folder, as opposed to using curl

now the new error is shown as `pickle.Unpicklingerror()` 
am i on the right path to debugging  ? or would u suggest reinstalling the nodes/comfy/ etc ? 
![CleanShot 2024-03-09 at 20 52 28](https://github.com/Acly/comfyui-inpaint-nodes/assets/10270460/4630c2a5-fd7d-462d-8539-48ab9a76a775)

**Comment by Acly** [comment]
yea it sounds like an issue with corrupted .pth file, you could check the sha256 to make sure the download worked?
