### ISSUE TITLE
Batch size issue

### ISSUE THREAD

**Issue by Latentnaut** [Acly/comfyui-inpaint-nodes#28]
I noticed I cannot create a batch with the node Repeat Latent Batch.

Is is possible to achive this in another way?

**Comment by Acly** [comment]
You can Repeat Latent Batch before passing it to the sampler as usual. What exactly is the issue?

**Comment by Latentnaut** [comment]
Here an example. For some reason Repeat Latent Batch is not giving me 4 images, only 1.

![image](https://github.com/Acly/comfyui-inpaint-nodes/assets/22867200/28aabf5d-d73e-4ba3-9fcf-69f4680b48cc)

**Comment by Acly** [comment]
Strange, it looks the same as what I tried, worked for me. Maybe something else influences it?

**Comment by Latentnaut** [comment]
I've took a second view and the Repeat Latent Batch is working well when I hook the Save node after de `VAE Decode`, as expected.

My failure was I hooked the Save node AFTER the` ImageCompositeMasked` node, obviously it was taking only the 1st generated image, so I thought the batch was not working well.

That's being said, I wonder why ImageCompositeMasked node is there, as I don't notice any difference. What is it useful for?

**Comment by Acly** [comment]
I would've expected `ImageCompositeMasked` to work on batches too.

It makes sure you get the original input image in places where the mask is 0. The output has gone through VAE encode + decode, which degrades quality.

**Comment by lldacing** [comment]
> I've took a second view and the Repeat Latent Batch is working well when I hook the Save node after de `VAE Decode`, as expected.
> 
> My failure was I hooked the Save node AFTER the` ImageCompositeMasked` node, obviously it was taking only the 1st generated image, so I thought the batch was not working well.
> 
> That's being said, I wonder why ImageCompositeMasked node is there, as I don't notice any difference. What is it useful for?

![image](https://github.com/Acly/comfyui-inpaint-nodes/assets/43737696/4ae16f54-de10-45fe-aab2-fc77ad1d9691)
you can do this
