### ISSUE TITLE
What if the repainted edges have visible seam marks?

### ISSUE THREAD

**Issue by jokero3answer** [Acly/comfyui-inpaint-nodes#3]
![微信截图_20240125224057](https://github.com/Acly/comfyui-inpaint-nodes/assets/130854108/919ce55a-0841-4525-a464-8f9ff276a28d)

**Comment by aimarxjg** [comment]
要再次小幅度重绘，它不是PS的AI（毕竟收费），最好的效果是图本身是AI画的，并且在使用它涂抹重绘时候还是调用绘制这张图的大模型，使用真实图片可能会出现比较明显的接缝
![QQ图片20240126091949](https://github.com/Acly/comfyui-inpaint-nodes/assets/132532636/bce2238b-f558-444b-ae1e-8a29a48486f0)
![QQ图片20240126091953](https://github.com/Acly/comfyui-inpaint-nodes/assets/132532636/b1554926-bd45-4e19-ae83-67b74285cedd)

**Comment by Acly** [comment]
Added advanced workflow with lots of options to pre-fill inpaint area and avoid seams.

**Comment by niko2020** [comment]
Does Lama has the "feature refinement" activated?
