### ISSUE TITLE
Padding size should be less than the corresponding input dimension

### ISSUE THREAD

**Issue by MarkoCa1** [Acly/comfyui-inpaint-nodes#30]
![image](https://github.com/Acly/comfyui-inpaint-nodes/assets/59492330/f4728db2-2862-4ae9-8430-f456ebda44a2)
![workflow](https://github.com/Acly/comfyui-inpaint-nodes/assets/59492330/596f0f45-06e1-47af-b803-577adb2bc7e4)
When I use a picture of 828*330 size and want to continue to expand the picture to the left and right, an error occurs. Is there any way to solve it? I like this node very much

**Comment by Acly** [comment]
Aspect ratios greater 2:1 were a problem, should be fixed now.
