### ISSUE TITLE
Inpaint (Using Model) Node is Not Functioning Properly

### ISSUE THREAD

**Issue by inferno46n2** [Acly/comfyui-inpaint-nodes#32]
If I use the built in mask editor in the Load Image node I get a vastly superior output versus using a mask that I load from an external source.

This basically makes this tool unusable for a large quantity of frames.

![image](https://github.com/Acly/comfyui-inpaint-nodes/assets/73665023/91f7fa1c-a795-4c6f-baf0-ad770c2ff236)

**Comment by Acly** [comment]
There's no technical difference. Maybe your input mask is degraded due to jpg compression so values that should be fully transparent are only 98% transparent or similar. Try using png or some other losless format.

**Comment by inferno46n2** [comment]
> There's no technical difference. Maybe your input mask is degraded due to jpg compression so values that should be fully transparent are only 98% transparent or similar. Try using png or some other losless format.

You are correct.

For anyone else that experiences this problem there is an easy fix. Kijai developed a node called "roundmask" which will round to the nearest int. E.g. if a part of your mask is only 98% transparent it will round that pixel area to 100%

You can find the node here [https://github.com/kijai/ComfyUI-KJNodes](url)

![image](https://github.com/Acly/comfyui-inpaint-nodes/assets/73665023/1d28be05-3adc-410e-9926-75feb5c58abc)
