### ISSUE TITLE
Doesn't work with impact pack detailer debug

### ISSUE THREAD

**Issue by cian0** [Acly/comfyui-inpaint-nodes#41]
Error occurred when executing DetailerForEachDebug:

The size of tensor a (58) must match the size of tensor b (72) at non-singleton dimension 3

From this library:
https://github.com/ltdrdata/ComfyUI-Impact-Pack/

It works when I use the unpatched model but not otherwise. Is there a way to use detailed inpainting?

**Comment by Acly** [comment]
I suspect it crops the image and you'd have to patch the model for each detailer mask using the cropped image & mask. I don't know if it's possible with that node.
