### ISSUE TITLE
ImportError: cannot import name 'LaMaArch' from 'spandrel.architectures.LaMa'

### ISSUE THREAD

**Issue by 925-Studio** [Acly/comfyui-inpaint-nodes#49]
After update I got this error message in terminal and the nodes were failed to load. Any ideas? Thanks.

**Comment by Acly** [comment]
The latest update is for compatibility with latest ComfyUI and does not work with older versions, so make sure you are up to date.

Also check spandrel is installed:
```
pip install --upgrade spandrel
```

**Comment by 925-Studio** [comment]
> pip install --upgrade spandrel

Yep, apparently it was the old version of spandrel caused the problem. After the update, the problem is gone. Thank you for the tip.
