### ISSUE TITLE
Installed nodes are not functional after setup

### ISSUE THREAD

**Issue by 295958090** [Acly/comfyui-inpaint-nodes#50]
Hello, I have installed the node but it remains non-functional despite my attempts. Updating to the latest version of ComfyUI did not resolve the issue, and even reverting to an older version of the node has not helped. Currently, other nodes I have installed are working properly. Could you please advise on how to address this problem? Many thanks.
![微信图片_20240528032433](https://github.com/Acly/comfyui-inpaint-nodes/assets/72679268/901de0cc-d17d-4c7d-ad85-40c446254443)

**Comment by Acly** [comment]
Please check ComfyUI output if the noads were loaded, and report the error message if they were not.
