### ISSUE TITLE
import failed

### ISSUE THREAD

**Issue by bats11** [Acly/comfyui-inpaint-nodes#51]
tryied both manager and git:

When loading the graph, the following node types were not found: 

    INPAINT_VAEEncodeInpaintConditioning
    INPAINT_LoadFooocusInpaint
    INPAINT_ApplyFooocusInpaint

Nodes that have failed to load will show as red on the graph.

**Comment by Acly** [comment]
1. Make sure to run the latest version of ComfyUI
2. Please check ComfyUI output if the nodes were loaded, and report the error message if they were not.

**Comment by ZongrongLi** [comment]
@Acly  the node is loaded , there is no error but these 3 nodes not found  
```

**Comment by ansonkao** [comment]
This is happening to me as well, and is present in a number of serverless infrastructure services (e.g. fal.ai/dashboard/comfy). There seems to have been an upstream change in the [comfyui](https://github.com/comfyanonymous/ComfyUI) repo, roughly 2 weeks ago, that causes these nodes to break. I'm not sure which commit, but a git bisect should find it

**Comment by Acly** [comment]
Sure there was, see #47 - but was already adapted a day later.
