### ISSUE TITLE
Help,Who has encountered this problem

### ISSUE THREAD

**Issue by LiuGe126** [Acly/comfyui-inpaint-nodes#52]
There is no way to install the node, either through the manager or directly download the decompression package, "comfyui-inpaint-nodes-main" already exists in "custom_nodes", but the node is still not installed.
![image](https://github.com/Acly/comfyui-inpaint-nodes/assets/165745548/7e815a23-69b0-4e99-868a-02efd4375e0c)
![image](https://github.com/Acly/comfyui-inpaint-nodes/assets/165745548/326862e2-9aa1-45e2-a76b-5a2207092aa7)

**Comment by Acly** [comment]
1. Make sure to run the latest version of ComfyUI
2. Please check ComfyUI output if the nodes were loaded, and report the error message if they were not.

**Comment by Leonerli2** [comment]
I have the same problem and it seems like some people are having it too in the last few hours. So maybe it's a general problem.
For me the import always fails on startup:
“0.0 seconds (IMPORT FAILED): D:\Confyui2\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-inpaint-nodes”
I reinstalled everything from scratch, including confyui, installed only the necessary costom nodes and checked the path for the models/inpaint forlder. But this is still the only error I get, so now I'm kinda out of ideas. 
![image](https://github.com/Acly/comfyui-inpaint-nodes/assets/145442228/807b1ff5-6dd6-48a4-b421-8c6de4c52b09)

**Comment by Acly** [comment]
Yes the recent updates need to match between ComfyUI and theses nodes, so lots of people running into this.

But I really need to see the error message (from ComfyUI console output) to help. It should be somewhere above the (IMPORT FAILED) message.

**Comment by LiuGe126** [comment]
> 查看错误消息(来自ComfyUI控制台输出)来提

I have confirmed that my version of confyui is the latest, and the node "inpaint nodes" seems to fail to load. This is my startup log, please check it.
[comfyui.log](https://github.com/Acly/comfyui-inpaint-nodes/files/15482336/comfyui.log)

**Comment by Acly** [comment]
The relevant error is:
```
ModuleNotFoundError: No module named 'spandrel'
Cannot import D:\AI\ComfyUI\ComfyUI_portbale\ComfyUI\custom_nodes\comfyui-inpaint-nodes-main module for custom nodes: No module named 'spandrel'
```

Solution:
```
pip install spandrel
```

> I have confirmed that my version of confyui is the latest

That's strange, because latest version of ComfyUI already requires spandrel, yet you don't have it installed.

**Comment by LiuGe126** [comment]
> The relevant error is:
> 
> ```
> ModuleNotFoundError: No module named 'spandrel'
> Cannot import D:\AI\ComfyUI\ComfyUI_portbale\ComfyUI\custom_nodes\comfyui-inpaint-nodes-main module for custom nodes: No module named 'spandrel'
> ```
> 
> Solution:
> 
> ```
> pip install spandrel
> ```
> 
> > I have confirmed that my version of confyui is the latest
> 
> That's strange, because latest version of ComfyUI already requires spandrel, yet you don't have it installed.

Sorry, I still don't know how to solve this problem. Can you explain it in more detail, or do you have a link or steps to a solution，thanks

**Comment by Leonerli2** [comment]
Thank you, this solves the problem. But be sure to install it to the right python version (the python embedded in confyui by setting the right path). I needed to install pip aswell for that python version. The whole confusion for me was because I have the exact same python version installed on my system and didnt notice that there was another version for confyui.
