### ISSUE TITLE
Whole image gets blurry

### ISSUE THREAD

**Issue by jffaust** [Acly/comfyui-inpaint-nodes#54]
I've had good results inpainting with this node pack but I noticed that the whole image gets gradually more blurry, even outside of the masked area. I'm using the simple workflow provided in the repo. Is this something that would be avoided but the more advanced workflows?

**Comment by Acly** [comment]
You can use `ImageCompositeMasked` node to avoid changes outside the masked area. It's part of the other example workflows.
