### ISSUE TITLE
where can i get the Places_512_FullData_G.pth in new workflow

### ISSUE THREAD

**Issue by whmc76** [Acly/comfyui-inpaint-nodes#6]
![image](https://github.com/Acly/comfyui-inpaint-nodes/assets/129386342/6f5d4e30-2434-4587-9a8b-176bb1d1b7c4)

**Comment by Acly** [comment]
MAT model listed [here](https://github.com/Acly/comfyui-inpaint-nodes?tab=readme-ov-file#inpaint-models-lama-mat)

I also split the [example workflows](https://github.com/Acly/comfyui-inpaint-nodes?tab=readme-ov-file#example-workflows) so there is now a simpler one which just shows Refine (<1 denoise) workflow without requiring MAT/LaMa
