### ISSUE TITLE
Why did I execute it and there was no change?

### ISSUE THREAD

**Issue by huanghe90909** [Acly/comfyui-inpaint-nodes#60]
![20240619215007](https://github.com/Acly/comfyui-inpaint-nodes/assets/173276003/b033f78c-79bc-4d0b-8ef1-549275da10b4)

**Comment by xThIsIsBoToXx** [comment]
Looks like you painted into the image, but not as a mask

**Comment by Acly** [comment]
Yes this image has the mask painted in for demonstration purposes, you need to re-paint the mask if you put it in a workflow.
