### ISSUE TITLE
Why doesn't this node work with a mask input that isnt from the Load image node?

### ISSUE THREAD

**Issue by xThIsIsBoToXx** [Acly/comfyui-inpaint-nodes#61]
As stated above, why doesn't it work with a mask I generated with RemBG for example? I attached my workflow below
![Screenshot 2024-06-25 132107](https://github.com/Acly/comfyui-inpaint-nodes/assets/28365563/3a4314ac-959f-4955-bca9-f0c8ddee5b17)
[TestBG.json](https://github.com/user-attachments/files/15970146/TestBG.json)

**Comment by Acly** [comment]
It should work with masks from any source. Is it possible the mask isn't perfectly white (eg. 0.98 instead of 1.0)?

**Comment by xThIsIsBoToXx** [comment]
Seems like that fixed it by the way, still seems impossible to actually remove stuff. It always generates something in for me unfortunately. I have seen people adjusting their prompt for the background but it doesnt seem to work super well for me.
