### ISSUE TITLE
ReleasesID :521421f,Cannot be loaded “inpaint_v26.fooocus.patch” format file

### ISSUE THREAD

**Issue by nkinfe** [Acly/comfyui-inpaint-nodes#65]
ReleasesID :521421f ,Unrecognized “inpaint_v26.fooocus.patch” format.Cannot be loaded

**Comment by nkinfe** [comment]
Comfyui ReleasesID :521421f

**Comment by rphly** [comment]
Seeing a similar issue where patch is not detected despite being in `/inpaint`
![Screenshot 2024-07-15 at 1 04 08 PM](https://github.com/user-attachments/assets/e66d99a4-b497-4d23-b0c5-0d3bd45ec71c)

**Comment by rphly** [comment]
Solved. For anyone who faces this issue, rename your .patch files to .safetensors and it will appear!

**Comment by JimWang151** [comment]
> Comfyui ReleasesID :521421f
 
Same at my side.Did you solve this problem?

**Comment by JimWang151** [comment]
> Comfyui ReleasesID :521421f

https://github.com/Acly/comfyui-inpaint-nodes/issues/66

This is the best solution to solve this problem.
