### ISSUE TITLE
i am facing some issues while i was running inpaint using model node please try to help me 

### ISSUE THREAD

**Issue by ayush1268** [Acly/comfyui-inpaint-nodes#68]
Error occurred when executing INPAINT_InpaintWithModel:

'str' object has no attribute 'id'

File "/home/studio-lab-user/ComfyUI/execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "/home/studio-lab-user/ComfyUI/execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "/home/studio-lab-user/ComfyUI/execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "/home/studio-lab-user/ComfyUI/custom_nodes/comfyui-inpaint-nodes/nodes.py", line 368, in inpaint
elif inpaint_model.architecture.id == "LaMa":

**Comment by ayush1268** [comment]
![Uploading ComfyUI - Google Chrome 14-07-2024 14_35_25.png…]()

**Comment by LL020202** [comment]
I also encountered the same problem.
Downloaded the model [LaMa](https://github.com/advimman/lama) | [Model download](https://github.com/Sanster/models/releases/download/add_big_lama/big-lama.pt) from the LaMa download address you provided
And put it in the specified location models/inpaint/big-lama.pt

elif inpaint_model.architecture.id == "LaMa":
AttributeError: 'str' object has no attribute 'id'

I changed it to inpaint_model.architecture and successfully solved the problem, but a new problem appeared

File "/data/custom_nodes/comfyui-inpaint-nodes/nodes.py", line 417, in inpaint
inpaint_model.cpu()
^^^^^^^^^^^^^^^^^
AttributeError: 'MaskedImageModelDescriptor' object has no attribute 'cpu'

**Comment by LL020202** [comment]
Your code is correct, there is no problem. I found my problem, it is spandrel 0.1.6 package is too old, I don't know why there is such an old package, I updated it to the latest one and it can run normally, thank you

pip install -U spandrel
