### ISSUE TITLE
Artifacts in pony-based models

### ISSUE THREAD

**Issue by Georgvadis** [Acly/comfyui-inpaint-nodes#70]
### Artifacts

![Снимок экрана 2024-07-24 162322](https://github.com/user-attachments/assets/65e3507c-f4d9-477e-bccb-abdffa53fcf0)

### Node
The problem arises in this node because there is no way not to use the inpaint patch

![Снимок экрана 2024-07-24 162328](https://github.com/user-attachments/assets/30aa836a-904c-4f21-8c18-2ee53f749417)

### Workflow
![Снимок экрана 2024-07-24 162336](https://github.com/user-attachments/assets/bf4d5aa3-d1ec-4944-b3dd-4f80281b16da)

### Solution
There is a node in this repository that allows you to set the inpaint engine to "none", which solves the problem with Pony-based models.
https://github.com/Seedsa/Fooocus_Nodes

![Снимок экрана 2024-07-24 155720](https://github.com/user-attachments/assets/a1502fb6-d652-4709-92dd-bae0ae42ce6a)

**Comment by Acly** [comment]
If you don't want the inpaint patch there is no reason to use the node at all. 

I don't think there is an inpaint model for pony checkpoints yet, so no real solution is possible.

**Comment by Georgvadis** [comment]
It's strange in fooocus 2.5, if you turn on inpaint, and set the value to none in the inpaint engine, everything works without artifacts with pony models. Perhaps I do not fully understand the principle of operation of the node in ComfyUI, in any case, thank you for taking your time and responding to my request.

**Comment by Acly** [comment]
The purpose of this node is to apply the inpaint model/patch.

By setting inpaint engine to "none" you instruct fooocus to NOT apply any inpaint model/patch. Equivalent to not using the node.

Not having dedicated inpaint model doesn't mean you can't use a mask and only change part of the image. But you don't need the node for that.
