### ISSUE TITLE
I have successfully installed the node comfyui-inpaint-nodes, but my ComfyUI fails to load it successfully. What could be the reason for this?

### ISSUE THREAD

**Issue by chaohuei2020** [Acly/comfyui-inpaint-nodes#73]
I have successfully installed the node comfyui-inpaint-nodes, but my ComfyUI fails to load it successfully. What could be the reason for this?
![屏幕截图 2024-08-02 153309](https://github.com/user-attachments/assets/e2bc7ca3-051c-4609-ac06-2cd03ac0d551)
![屏幕截图 2024-08-02 153426](https://github.com/user-attachments/assets/28cbb3b1-60e5-4b9f-9f94-f71c3da862d5)
![屏幕截图 2024-08-02 153745](https://github.com/user-attachments/assets/a90610bb-bbe7-4eae-b84d-ec4b454b361d)

**Comment by AndiSandy** [comment]
0.2 seconds: D:\BaiduNetdiskDownload\ComfyUI\custom_nodes\ComfyUI-BiRefNet-ZHO
   0.2 seconds (IMPORT FAILED): D:\BaiduNetdiskDownload\ComfyUI\custom_nodes\comfyui-inpaint-nodes
   0.3 seconds: D:\BaiduNetdiskDownload\ComfyUI\custom_nodes\ComfyUI-Manager

**Comment by Acly** [comment]
Please scroll up in the ComfyUI output and find the error message. It should be somewhere above the (IMPORT FAILED).
