### ISSUE TITLE
patch type not recognized fooocus diffusion_model

### ISSUE THREAD

**Issue by Krishicall** [Acly/comfyui-inpaint-nodes#78]
Updated to latest Comfyui version and now getting this error- any help would be appreciated!

patch type not recognized fooocus diffusion_model.output_blocks.1.0.in_layers.2.weight
patch type not recognized fooocus diffusion_model.output_blocks.1.0.in_layers.2.bias
patch type not recognized fooocus diffusion_model.output_blocks.0.0.in_layers.2.weight
patch type not recognized fooocus diffusion_model.output_blocks.0.0.in_layers.2.bias
patch type not recognized fooocus diffusion_model.output_blocks.2.0.in_layers.2.weight
patch type not recognized fooocus diffusion_model.output_blocks.2.0.in_layers.2.bias
patch type not recognized fooocus diffusion_model.output_blocks.2.2.conv.weight
patch type not recognized fooocus diffusion_model.output_blocks.2.2.conv.bias
patch type not recognized fooocus diffusion_model.output_blocks.2.0.out_layers.3.weight
patch type not recognized fooocus diffusion_model.output_blocks.2.0.out_layers.3.bias
patch type not recognized fooocus diffusion_model.output_blocks.1.0.out_layers.3.weight
patch type not recognized fooocus diffusion_model.output_blocks.1.0.out_layers.3.bias
patch type not recognized fooocus diffusion_model.output_blocks.0.0.out_layers.3.weight
patch type not recognized fooocus diffusion_model.output_blocks.0.0.out_layers.3.bias
patch type not recognized fooocus diffusion_model.middle_block.2.out_layers.3.weight
patch type not recognized fooocus diffusion_model.middle_block.2.out_layers.3.bias
patch type not recognized fooocus diffusion_model.middle_block.2.in_layers.2.weight
patch type not recognized fooocus diffusion_model.middle_block.2.in_layers.2.bias
patch type not recognized fooocus diffusion_model.middle_block.0.out_layers.3.weight
patch type not recognized fooocus diffusion_model.middle_block.0.out_layers.3.bias
patch type not recognized fooocus diffusion_model.middle_block.0.in_layers.2.weight
patch type not recognized fooocus diffusion_model.middle_block.0.in_layers.2.bias
patch type not recognized fooocus diffusion_model.input_blocks.8.0.out_layers.3.weight
patch type not recognized fooocus diffusion_model.input_blocks.8.0.out_layers.3.bias
patch type not recognized fooocus diffusion_model.input_blocks.8.0.in_layers.2.weight
patch type not recognized fooocus diffusion_model.input_blocks.8.0.in_layers.2.bias
patch type not recognized fooocus diffusion_model.input_blocks.7.0.out_layers.3.weight
patch type not recognized fooocus diffusion_model.input_blocks.7.0.out_layers.3.bias
patch type not recognized fooocus diffusion_model.output_blocks.2.1.transformer_blocks.3.ff.net.0.proj.weight
patch type not recognized fooocus diffusion_model.output_blocks.2.1.transformer_blocks.3.ff.net.0.proj.bias
patch type not recognized fooocus diffusion_model.output_blocks.2.1.transformer_blocks.2.ff.net.0.proj.weight
patch type not recognized fooocus diffusion_model.output_blocks.2.1.transformer_blocks.2.ff.net.0.proj.bias
patch type not recognized fooocus diffusion_model.output_blocks.2.1.transformer_blocks.1.ff.net.0.proj.weight

**Comment by Acly** [comment]
There was a change in comfyui that wasn't compatible. Should work again now if you update the node.

**Comment by VantomPayne** [comment]
Seems like it's still not working.

**Comment by bananasss00** [comment]
Again this problem, but with latest torch 2.4.1 version:
```
[2024-09-03 22:21] Warning torch.load doesn't support weights_only on this pytorch version, loading unsafely.
[2024-09-03 22:21] [comfyui-easy-use] Injecting patched comfy.lora.calculate_weight.calculate_weight
[2024-09-03 22:21] Requested to load SDXL
[2024-09-03 22:21] Loading 1 new model
[2024-09-03 22:21] patch type not recognized fooocus diffusion_model.output_blocks.1.0.in_layers.2.weight
[2024-09-03 22:21] patch type not recognized fooocus diffusion_model.output_blocks.1.0.in_layers.2.bias
[2024-09-03 22:21] patch type not recognized fooocus diffusion_model.output_blocks.0.0.in_layers.2.weight
[2024-09-03 22:21] patch type not recognized fooocus diffusion_model.output_blocks.0.0.in_layers.2.bias
[2024-09-03 22:21] patch type not recognized fooocus diffusion_model.output_blocks.2.0.in_layers.2.weight
[2024-09-03 22:21] patch type not recognized fooocus diffusion_model.output_blocks.2.0.in_layers.2.bias
[2024-09-03 22:21] patch type not recognized fooocus diffusion_model.output_blocks.2.2.conv.weight
```
