### ISSUE TITLE
What should I do if 'Import node failed' is displayed after countless installations?

### ISSUE THREAD

**Issue by balumiisa** [Acly/comfyui-inpaint-nodes#80]
![20240828173958523](https://github.com/user-attachments/assets/1e032f8f-6102-4580-89af-3070bfb082ee)
![20240828173929303](https://github.com/user-attachments/assets/19a09123-fccb-4ee2-9f5e-a2437c8bd2ac)
What should I do if 'Import node failed' is displayed after countless installations?

**Comment by 1GRsheying** [comment]
同问！应该是依赖问题！怎么安装依赖

**Comment by Acly** [comment]
Check the ComfyUI output (in console) for the error message. It should be printed right at start up (before the IMPORT FAILED).

**Comment by balumiisa** [comment]
> 同问！应该是依赖问题！怎么安装依赖

我这两天才为了SUPIR重装了环境依赖，最快的是在秋叶大佬的启动器里面找到高级选项，重装pytorch和其他东西。但是装好之后inpaint就导入失败了，不知道是不是哪里冲突了。

**Comment by balumiisa** [comment]
> Check the ComfyUI output (in console) for the error message. It should be printed right at start up (before the IMPORT FAILED).

![20240829090933137](https://github.com/user-attachments/assets/ec14f84a-c8bf-45df-bcfd-38f7fd13b0b7)
![20240829092349681](https://github.com/user-attachments/assets/99ca9dc3-44d1-45f9-91e6-a9671ebceba8)
The reason for the error is that comfyUI needs to be updated, but the manager checks that it is already the latest version.

**Comment by 1GRsheying** [comment]
版本跟新了！就好了  谢谢

**Comment by balumiisa** [comment]
> 版本跟新了！就好了 谢谢

咋更新？我这显示已经是最新的啦。。。
