### ISSUE TITLE
preserve 100% of the inpaint area ?

### ISSUE THREAD

**Issue by BenDes21** [Acly/comfyui-inpaint-nodes#82]
Hi there, trying to use a1111 + adetailer + inpaint for automatically detect a part of the body of my model ( let's said the arms ) and handwrite a specific text on it ( tattoo style ). The issue is that adetailer not support soft inpainting so the area ( skin ) change a lot if I want that my text appear. I created a comfyUI workflow Samloader for the detection of the partof the body  + the lama inpaint model + inpaintmodelconditionning but same problem happen : the text is correctly writed in the detect area but the inpaint just change too much the skin / details. Would like to know if its possible to preserve the area and just write " inside the mask " 

Thanks

**Comment by Acly** [comment]
It sounds a bit contradictory, if you preserve 100% of the inpaint area nothing can change.

I think you need a 2 steps:
* Mask the arm. Inpaint. Some skin will also change.
* Mask only the new text. Replace pixels outside mask with original image.

**Comment by BenDes21** [comment]
[](url)> It sounds a bit contradictory, if you preserve 100% of the inpaint area nothing can change.
> 
> I think you need a 2 steps:
> 
> * Mask the arm. Inpaint. Some skin will also change.
> * Mask only the new text. Replace pixels outside mask with original image.

Hi,

Mask the arm. Inpaint. Some skin will also change. => the area of the skin change too much, and if I lower the denoise my text is not accurate

Mask only the new text. Replace pixels outside mask with original image. => How ? The text come from a prompt who go directly to the inpaint node :/

My only solution is to reduce the size of the mask, reshape it into a rectangle and move it into a flat skin area where the inpainting will not cause so much change but I don't know who to " move the mask " up 

<img width="681" alt="Untitled" src="https://github.com/user-attachments/assets/ef0d29e9-43b4-45df-b598-16f444588ec1">

**Comment by BenDes21** [comment]
> > It sounds a bit contradictory, if you preserve 100% of the inpaint area nothing can change.
> 
> > I think you need a 2 steps:
> > 
> > * Mask the arm. Inpaint. Some skin will also change.
> > * Mask only the new text. Replace pixels outside mask with original image.
> 
> Hi,
> 
> Mask the arm. Inpaint. Some skin will also change. => the area of the skin change too much, and if I lower the denoise my text is not accurate, also it's need to be auto so the area is detect -> auto inpaint
> 
> Mask only the new text. Replace pixels outside mask with original image. => How ? The text come from a prompt who go directly to the inpaint node :/
> 
> My only solution is to reduce the size of the mask, reshape it into a rectangle and move it into a flat skin area where the inpainting will not cause so much change but I don't know who to " move the mask " up
> 
> <img alt="Untitled" width="681" src="https://private-user-images.githubusercontent.com/153294763/364672387-ef0d29e9-43b4-45df-b598-16f444588ec1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MjIwOTUsIm5iZiI6MTcyNTUyMTc5NSwicGF0aCI6Ii8xNTMyOTQ3NjMvMzY0NjcyMzg3LWVmMGQyOWU5LTQzYjQtNDVkZi1iNTk4LTE2ZjQ0NDU4OGVjMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNVQwNzM2MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OWNhMTE0YzkyNDczZTZlNTFmOGE1YjMzMjU5ZjhjNTFmZTI1NmQ5MjE4NWE5ZTZjZWY0NDcxZWJlOTAyZWM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GqyxmIt-nr1grIwEaqKsxMAhuo2V3bugwKrnxlVWEFY">

**Comment by Acly** [comment]
> How ? The text come from a prompt who go directly to the inpaint node :/

Yes. That's why you need 2 steps.

First do the inpaint (on arm/face/whatever).

Then AFTER the inpaint, when you have the text: create a new mask for the text, and restore the old arm/skin/face. You don't need inpaint for that. Just replace with the original image.

**Comment by BenDes21** [comment]
> > How ? The text come from a prompt who go directly to the inpaint node :/
> 
> Yes. That's why you need 2 steps.
> 
> First do the inpaint (on arm/face/whatever).
> 
> Then AFTER the inpaint, when you have the text: create a new mask for the text, and restore the old arm/skin/face. You don't need inpaint for that. Just replace with the original image.

Thanks for the answer, so after the inpainting I link ksampler inpainted + vae decode into let's said segmentanythingv2 for detect the text then create a mask of it. 

 So I have the original image, the image inpainted ( text on the input image ) and the mask of the text.
 

Sorry but Im not ultra confortable with comfyUI for the moment, what's the next step when I have my mask text + the original image, simply blend them ?

**Comment by Acly** [comment]
Yes, `ImageCompositeMasked` node should work I think. You may want to grow/feather the mask for smoother transition.

**Comment by BenDes21** [comment]
> Yes, `ImageCompositeMasked` node should work I think. You may want to grow/feather the mask for smoother transition.

alright thanks, getting ```
ImageCompositeMasked
The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 1 , will try to find out. Thanks for your help 
```
