### ISSUE TITLE
The generated result does not match the original image and is very poor

### ISSUE THREAD

**Issue by 515753541** [Acly/comfyui-inpaint-nodes#86]
I tried to redraw a foreground, but it didn't work very well

![ComfyUI_temp_ciaot_00007_](https://github.com/user-attachments/assets/246d6e2a-c1aa-46e3-8410-c59e703c51a8)

![ComfyUI_temp_ciaot_00006_](https://github.com/user-attachments/assets/96016a30-f3f8-46c5-b130-b08173f673b0)

This is my workflow
![image](https://github.com/user-attachments/assets/e2fcb7e1-afca-4665-a185-150e491356ae)

**Comment by Acly** [comment]
There haven't been any ComfyUI changes affecting the nodes, it works as before.

The issue is because a distilled checkpoint (Lightning) was used. The inpaint model only works with regular checkpoints and step count.
