### ISSUE TITLE
VAE Encode & inpaint conditioning stopped working

### ISSUE THREAD

**Issue by A7med3mar96** [Acly/comfyui-inpaint-nodes#98]
I've just updated all of my comfyui (including the comfyui-inpaint-nodes) and my workflow stopped working 
![Screenshot 2024-11-19 160833](https://github.com/user-attachments/assets/11ec852b-97a5-47c6-96cd-ffe0ddb6b157)

**Comment by Acly** [comment]
Was fixed here: https://github.com/Acly/comfyui-inpaint-nodes/commit/9e9222d2fa851f77afeeb7ce0310d6edd9fb78ee

Maybe need to update again :D was a comfy update earlier today which broke it.
