### ISSUE TITLE
nodes.InpaintModelConditioning().encode called with add_noise_mask

### ISSUE THREAD

**Issue by btaens** [Acly/comfyui-inpaint-nodes#99]
In the latest update, InpaintModelConditioning.encode gained a noise_mask attribute.

The latest update to this repo included this modification when calling it, however, it uses "add_noise_mask" for the name of the argument at nodes.py, line 218, . This should be "noise_mask".

Because of this, it currently errors out with a TypeError, because it falls back to the old way of calling encode(), which then throws the TypeError.

**Comment by Acly** [comment]
ah, it was "add_noise_mask" for a whole 8 hours before change of heart apparently
